### ISSUE TITLE
Handle deposit failure better

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra-v2#229]
If we try to deposit and we have tokens but not enough eth to pay gas, the deposit will fail.

If that account gets eth later & we try to deposit again, we're stuck in a state like this:

```
2019-08-03T20:21:30.855872226Z (node:69) UnhandledPromiseRejectionWarning: Error: Error: Error: Cannot deposit while another deposit is occurring in the channel.
2019-08-03T20:21:30.855888791Z     at DepositController.<anonymous> (/root/node_modules/@connext/client/dist/controllers/DepositController.js:66:23)
2019-08-03T20:21:30.855894695Z     at Generator.throw (<anonymous>)
2019-08-03T20:21:30.855911793Z     at rejected (/root/node_modules/@connext/client/dist/controllers/DepositController.js:5:65)
2019-08-03T20:21:30.855918194Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by svetlanama** [comment]
Other cases:
1. If you deposited more than minimum, you will get into an infinite error loop:
```
Attempting to deposited more than the limit: 2.0 > Ξ0.134
```
2. When the new amount comes, but some of the deposit exists, you will get into an infinite error loop:
```
[Error] Unhandled Promise Rejection: Error: Error: Error: Cannot deposit while another deposit is occurring in the channel.
    dispatchException (2.75ba622d.chunk.js:1:742348)
    (anonymous function) (2.75ba622d.chunk.js:1:738602)
    n (2.75ba622d.chunk.js:1:62628)
    f (2.75ba622d.chunk.js:1:62867)
    promiseReactionJob
```

**Comment by hthillman** [comment]
@bohendo has there been movement here? I think this may have been resolved?

**Comment by hthillman** [comment]
cc @rhlsthrm @LayneHaber

**Comment by rhlsthrm** [comment]
I believe this is still an issue.

**Comment by LayneHaber** [comment]
This is an inflight deposit issue, moved the discussion around how to handle those [here](https://github.com/ConnextProject/indra/issues/237)

The infinite error loops with deposit boundaries have been solved at the card level, but you will still have in flight errors
