### ISSUE TITLE
Deposit not increasing balance by right amount

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra-v2#230]
Seeing the following on my tip bot, not really sure why

```
2019-08-04T05:06:36.703344602Z (node:518) UnhandledPromiseRejectionWarning: Error: Error: My balance was not increased by the deposit amount.
2019-08-04T05:06:36.703372266Z     at DepositController.<anonymous> (/root/node_modules/@connext/client/dist/controllers/DepositController.js:66:23)
2019-08-04T05:06:36.703383660Z     at Generator.next (<anonymous>)
2019-08-04T05:06:36.703391868Z     at fulfilled (/root/node_modules/@connext/client/dist/controllers/DepositController.js:4:58)
2019-08-04T05:06:36.703404737Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hthillman** [comment]
Has this been resolved?

**Comment by LayneHaber** [comment]
Havent personally seen this in a while, my guess is it was resolved with the counterfactual create channel upgrades.

Closing until it pops up again
